### PR TITLE
fix stream for a single barcode

### LINKED ISSUE #112: Fix store.stream(key)
I'd like to undeprecate Observable<T> stream(V id).  The adjusted functionality will be an endless stream that emits new network values coming through a store for a particular barcode. Stream allows you to stay subscribed in many places and then calling fetch(key)  to get them all a new value. Implementation will be similar to getRefreshing but will instead hook into new network values.

The difference between getRefreshing(key) & stream(key) is that getRefreshing will repeat when clear is called while stream will repeat when anything hits the fetcher again.

### PR DESCRIPTION
**Pull request by digitalbuddha**
This pr fixes the functionality of stream(key) which will now kick off a get request and then propogate a new network value anytime it comes through the store for the same key.

closes #112

### CODE REVIEW

File: filesystem/src/main/java/com/nytimes/android/external/fs3/SourcePersisterFactory.java [hunk 1]
```diff
@@ -78,4 +78,6 @@ private SourcePersisterFactory() {
         return SourcePersister.create(fileSystem);
     }
 
+
+
```
Comment (tiwiz) [inline filesystem/src/main/java/com/nytimes/android/external/fs3/SourcePersisterFactory.java]: 3 empty lines seem a bit odd?

File: store/src/main/java/com/nytimes/android/external/store3/base/impl/RealInternalStore.java [hunk 2]
```diff
@@ -211,15 +212,21 @@ void notifySubscribers(Parsed data) {
     @Nonnull
     @Override
     public Observable<Parsed> stream(@Nonnull Key key) {
```
Comment (tiwiz) [inline store/src/main/java/com/nytimes/android/external/store3/base/impl/RealInternalStore.java:244]: Might the `stream` name that return an `Observable` cause a little bit of confusion with Java 8 `Stream` API?

File: store/src/main/java/com/nytimes/android/external/store3/base/impl/RealInternalStore.java [hunk 3]
```diff
@@ -79,7 +80,7 @@
     public Observable<Parsed> getRefreshing(@Nonnull final Key key) {
         return get(key)
                 .toObservable()
-                .compose(StoreUtil.<Parsed, Key>repeatWhenCacheEvicted(refreshSubject, key));
+                .compose(StoreUtil.<Parsed, Key>repeatWhenSubjectEmits(refreshSubject, key));
```
Comment (tiwiz) [inline store/src/main/java/com/nytimes/android/external/store3/base/impl/RealInternalStore.java:89]: We get an `Observable`, we convert it to a `Single` and then back to `Observable`?

File: store/src/test/java/com/nytimes/android/external/store3/StreamOneKeyTest.java [hunk 4]
```diff
@@ -0,0 +1,85 @@
...
+
+        when(persister.write(barCode, TEST_ITEM))
+                .thenReturn(Single.just(true));
+        when(persister.write(barCode, TEST_ITEM2))
+                .thenReturn(Single.just(true));
+    }
+
+    @Test
+    public void testStream() {
+        TestObserver<String> streamObservable = store.stream(barCode).test();
```
Comment (tiwiz) [inline store/src/test/java/com/nytimes/android/external/store3/StreamOneKeyTest.java:64]: Can we check that it calls the correct methods?

File: store/src/test/java/com/nytimes/android/external/store3/StreamOneKeyTest.java [hunk 5]
```diff
@@ -0,0 +1,85 @@
...
+        //get for another barcode should not trigger a stream for barcode1
+        when(fetcher.fetch(barCode2))
+                .thenReturn(Single.just(TEST_ITEM));
+        when(persister.read(barCode2))
+                .thenReturn(Maybe.empty())
+                .thenReturn(Maybe.just(TEST_ITEM));
+        when(persister.write(barCode2, TEST_ITEM))
+                .thenReturn(Single.just(true));
+        store.get(barCode2).test().awaitCount(1);
+        streamObservable.assertValueCount(2);
```
Comment (tiwiz) [inline store/src/test/java/com/nytimes/android/external/store3/StreamOneKeyTest.java:83]: Can we check that we are calling the correct methods?

File: store/src/main/java/com/nytimes/android/external/store3/base/impl/RealInternalStore.java (hunk 2 above)
Comment (digitalbuddha) [reply store/src/main/java/com/nytimes/android/external/store3/base/impl/RealInternalStore.java:244]: breaking change will leave.

File: store/src/test/java/com/nytimes/android/external/store3/StreamOneKeyTest.java (hunk 5 above)
Comment (digitalbuddha) [reply store/src/test/java/com/nytimes/android/external/store3/StreamOneKeyTest.java:83]: by asserting the results it will only succeed if proper methods on persister and fetcher were called.

File: store/src/main/java/com/nytimes/android/external/store3/base/impl/RealInternalStore.java (hunk 3 above)
Comment (digitalbuddha) [reply store/src/main/java/com/nytimes/android/external/store3/base/impl/RealInternalStore.java:89]: ugh yes this needs to be cleaned up. will do it in another pr good catch!

File: store/src/main/java/com/nytimes/android/external/store3/base/impl/RealInternalStore.java (hunk 2 above)
Comment (tiwiz) [reply store/src/main/java/com/nytimes/android/external/store3/base/impl/RealInternalStore.java:244]: Maybe a little bit of documentation could help, tho?

File: store/src/test/java/com/nytimes/android/external/store3/StreamOneKeyTest.java (hunk 5 above)
Comment (tiwiz) [reply store/src/test/java/com/nytimes/android/external/store3/StreamOneKeyTest.java:83]: But a few assertions more could serve as documentation for the future, so that we don't forget about the flow :-)

**Review by ramonaharrison — APPROVED** [review]
