### PR TITLE
clear needs to clear noop disk and inflight

### LINKED ISSUE #96: Clear Memory Fails
After clearing the memory a following call to `get` should make a new request. But it doesn't

See #95

### PR DESCRIPTION
**Pull request by digitalbuddha**
closes #96  
@PaulWoitaschek you find em I fix em? :-)

### CODE REVIEW

File: store/src/main/java/com/nytimes/android/external/store/base/impl/RealInternalStore.java [hunk 1]
```diff
@@ -265,6 +266,14 @@ void updateMemory(@Nonnull final BarCode barCode, final Parsed data) {
     @Override
     public void clearMemory() {
         memCache.invalidateAll();
+        inFlightRequests.invalidateAll();
```
Comment (pavlospt) [inline store/src/main/java/com/nytimes/android/external/store/base/impl/RealInternalStore.java]: Shouldn't you clear the inflight requests first in case there is one that successes and writes in memory after you have cleared it and before you invalidate the inFlight ones?

Comment (digitalbuddha) [inline store/src/main/java/com/nytimes/android/external/store/base/impl/RealInternalStore.java]: Yup you're right
