### PR TITLE
Fix NoopPersister wrong caching duration

### LINKED ISSUE #150: MO no op MO problems
#149 raises another interesting issue. If the mem cache is less than a minute the in flight denouncer also needs to be adjusted. Secondly the no op persister needs to be migrated to use a guava cache which has same policy as mem cache.

### PR DESCRIPTION
**Pull request by pavlospt**
Attempt to fix #150. Seems to be working from my testing. Let me know what you think and what could have been done better!

### CODE REVIEW

**Review by digitalbuddha — COMMENTED** [review]
wow thank you so much for this! Ok so theres 1 more whole you can configure the cache to have `                .maximumSize()` Ideally the no op persister would respect this limit as well.  Since we have 3 fields to pass through lets make a `MemoryConfig` java object that will have the 3 fields "size, duration, unit" or some similar name.  Thank you again overall looks solid.

**Comment by pavlospt** [comment]
@digitalbuddha yeah that sounds great. Would definitely do that tomorrow and push again!

**Comment by pavlospt** [comment]
Will also fix the Travis issues on the same commit!

File: app/src/main/java/com/nytimes/android/sample/SampleApp.java [hunk 1]
```diff
@@ -57,11 +61,16 @@ private void initPersister() {
...
+                .fetcher(new Fetcher<RedditData, BarCode>() {
+                    @Nonnull
+                    @Override
+                    public Observable<RedditData> fetch(@Nonnull BarCode barCode) {
+                        Log.d("fetcher", "Going for fetcher");
+                        return provideRetrofit().fetchSubreddit(barCode.getKey(), "10");
+                    }
+                })
+//                .fetcher(barCode -> provideRetrofit().fetchSubreddit(barCode.getKey(), "10"))
+                .memory(10, TimeUnit.SECONDS)
```
Comment (digitalbuddha) [inline app/src/main/java/com/nytimes/android/sample/SampleApp.java]: lets change method name to `memoryPolicy`

File: store/src/main/java/com/nytimes/android/external/store/base/impl/RealInternalStore.java [hunk 2]
```diff
@@ -53,41 +53,60 @@
...
+        this.fetcher = fetcher;
+        this.persister = persister;
+        this.parser = parser;
+        this.memCache = CacheBuilder
+                .newBuilder()
+                .expireAfterWrite(expireAfter, expireAfterTimeUnit)
+                .build();
+        this.stalePolicy = stalePolicy;
+        this.inFlightRequests = CacheBuilder.newBuilder()
+                .expireAfterWrite(expireAfter, expireAfterTimeUnit)
```
Comment (digitalbuddha) [inline store/src/main/java/com/nytimes/android/external/store/base/impl/RealInternalStore.java]: in flight request should not necessarily be same as memory, its more that it should be the max(1 minute, memory limit)

File: store/src/main/java/com/nytimes/android/external/store/base/impl/RealInternalStore.java [hunk 3]
```diff
@@ -53,41 +53,60 @@
...
         this.parser = parser;
-        this.memCache = memCache;
+        this.memCache = CacheBuilder
+                .newBuilder()
+                .expireAfterWrite(getCacheTTL(), getCacheTTLTimeUnit())
+                .build();
         this.stalePolicy = stalePolicy;
-        inFlightRequests = CacheBuilder.newBuilder()
-                .expireAfterWrite(TimeUnit.MINUTES.toSeconds(1), TimeUnit.SECONDS)
+        this.inFlightRequests = CacheBuilder.newBuilder()
```
Comment (digitalbuddha) [inline store/src/main/java/com/nytimes/android/external/store/base/impl/RealInternalStore.java]: remove the `this` no reason for it

File: store/src/main/java/com/nytimes/android/external/store/base/impl/RealInternalStore.java [hunk 4]
```diff
@@ -53,41 +53,60 @@
...
+                .expireAfterWrite(getCacheTTL(), getCacheTTLTimeUnit())
                 .build();
 
-        subject = BehaviorSubject.create();
+        this.subject = BehaviorSubject.create();
```
Comment (digitalbuddha) [inline store/src/main/java/com/nytimes/android/external/store/base/impl/RealInternalStore.java]: remove `this`

File: store/src/main/java/com/nytimes/android/external/store/base/impl/RealStoreBuilder.java [hunk 5]
```diff
@@ -25,8 +25,9 @@
 public class RealStoreBuilder<Raw, Parsed, Key> {
     private final List<KeyParser> parsers = new ArrayList<>();
     private Persister<Raw, Key> persister;
-    private Cache<Key, Observable<Parsed>> memCache;
     private Fetcher<Raw, Key> fetcher;
+    private long expireAfter = 0;
+    private TimeUnit expireAfterTimeUnit = null;
```
Comment (brianPlummer) [inline store/src/main/java/com/nytimes/android/external/store/base/impl/RealStoreBuilder.java]: it might be a better approach to initialize this to a non-null value and set the expireAfter to a -1,  you can validate the input for memory() to guarantee non-nullness.  this would alleviate the need for null checking below.  another approach is to have the memory() method set a flag and use the passed in values for the builder (validate within memory() and just check flag below for inclusion...no need for validation..)

**Comment by brianPlummer** [comment]
Thank you @pavlospt  for taking a stab at this!!! :)))))

File: store/src/main/java/com/nytimes/android/external/store/base/impl/RealStoreBuilder.java (hunk 5 above)
Comment (pavlospt) [reply store/src/main/java/com/nytimes/android/external/store/base/impl/RealStoreBuilder.java]: @brianPlummer yes, that sounds great as well!

File: store/src/main/java/com/nytimes/android/external/store/base/impl/RealInternalStore.java (hunk 3 above)
Comment (pavlospt) [reply store/src/main/java/com/nytimes/android/external/store/base/impl/RealInternalStore.java]: Will do!

File: store/src/main/java/com/nytimes/android/external/store/base/impl/RealInternalStore.java (hunk 4 above)
Comment (pavlospt) [reply store/src/main/java/com/nytimes/android/external/store/base/impl/RealInternalStore.java]: Same here!

File: store/src/main/java/com/nytimes/android/external/store/base/impl/RealInternalStore.java (hunk 2 above)
Comment (pavlospt) [reply store/src/main/java/com/nytimes/android/external/store/base/impl/RealInternalStore.java]: Sounds reasonable.

**Comment by pavlospt** [comment]
@digitalbuddha @brianPlummer I added the changes we discussed. Let me know what you think. Tests are fine and seems to be working from testing on a real device as well!

**Comment by pavlospt** [comment]
@digitalbuddha there is a remaining issue with PMD, that I don't really know how to fix. Any ideas? 
screen shot 2017-03-09 at 12 02 32

**Comment by digitalbuddha** [comment]
Sadness. You can do a Pmd suppress warnings on the class. I guess we need
to refactor some stuff going forward.

File: app/src/main/java/com/nytimes/android/sample/SampleApp.java [hunk 6]
```diff
@@ -57,11 +61,23 @@ private void initPersister() {
...
+                    @Nonnull
+                    @Override
+                    public Observable<RedditData> fetch(@Nonnull BarCode barCode) {
+                        Log.d("fetcher", "Going for fetcher");
+                        return provideRetrofit().fetchSubreddit(barCode.getKey(), "10");
+                    }
+                })
+//                .fetcher(barCode -> provideRetrofit().fetchSubreddit(barCode.getKey(), "10"))
+                .memoryPolicy(
+                    MemoryPolicy
```
Comment (digitalbuddha) [inline app/src/main/java/com/nytimes/android/sample/SampleApp.java]: Let's simplify this to MemoryPolicy.builder() which then returns an instance of the new builder.

**Review by digitalbuddha — COMMENTED** [review]
Need to get this reviewed internally.

File: app/src/main/java/com/nytimes/android/sample/SampleApp.java (hunk 6 above)
Comment (pavlospt) [reply app/src/main/java/com/nytimes/android/sample/SampleApp.java]: Ok will do in a bit!

**Comment by digitalbuddha** [comment]
Will review in more detail today.

File: app/src/main/java/com/nytimes/android/sample/SampleApp.java (hunk 6 above)
Comment (pavlospt) [reply app/src/main/java/com/nytimes/android/sample/SampleApp.java]: Done!

File: app/src/main/java/com/nytimes/android/sample/SampleApp.java [hunk 7]
```diff
@@ -57,11 +61,22 @@ private void initPersister() {
...
-                .fetcher(barCode -> provideRetrofit().fetchSubreddit(barCode.getKey(), "10"))
-                .memory(CacheBuilder.newBuilder()
-                        .maximumSize(1)
-                        .expireAfterWrite(10, TimeUnit.SECONDS)
-                        .build())
+                .fetcher(new Fetcher<RedditData, BarCode>() {
+                    @Nonnull
+                    @Override
+                    public Observable<RedditData> fetch(@Nonnull BarCode barCode) {
+                        Log.d("fetcher", "Going for fetcher");
```
Comment (alexio) [inline app/src/main/java/com/nytimes/android/sample/SampleApp.java]: Remove log and switch back to lambda.

File: store/src/main/java/com/nytimes/android/external/store/base/impl/MemoryPolicy.java [hunk 8]
```diff
@@ -0,0 +1,62 @@
+package com.nytimes.android.external.store.base.impl;
+
+
+import java.util.concurrent.TimeUnit;
+
+public class MemoryPolicy {
```
Comment (alexio) [inline store/src/main/java/com/nytimes/android/external/store/base/impl/MemoryPolicy.java]: Since this is a public class, a javadoc would be appreciated. Could you write class/method comments where appropriate?

Comment (pavlospt) [reply store/src/main/java/com/nytimes/android/external/store/base/impl/MemoryPolicy.java]: Ok will do!

File: app/src/main/java/com/nytimes/android/sample/SampleApp.java (hunk 7 above)
Comment (pavlospt) [reply app/src/main/java/com/nytimes/android/sample/SampleApp.java]: Sure

Comment (alexio) [reply app/src/main/java/com/nytimes/android/sample/SampleApp.java]: Thanks! 👍

File: store/src/main/java/com/nytimes/android/external/store/base/impl/RealInternalStore.java [hunk 9]
```diff
@@ -53,40 +53,79 @@
...
+        this.fetcher = fetcher;
+        this.persister = persister;
+        this.parser = parser;
+        this.stalePolicy = stalePolicy;
+
+        initMemCache(memoryPolicy);
+        initFlightRequests(memoryPolicy);
+
+        subject = BehaviorSubject.create();
     }
```
Comment (cybo42) [inline store/src/main/java/com/nytimes/android/external/store/base/impl/RealInternalStore.java]: Minor consideration, since this `init()` is almost the same as the one below, with the exception of creating the `defaultMemoryPolicy`, maybe consolidate the two, adding a conditional to configure a default `MemoryPolicy` if the none was passed in (or `null` passed in).  It may also make sense to move this into a constructor, since nothing else calls `init()`.

Comment (pavlospt) [reply store/src/main/java/com/nytimes/android/external/store/base/impl/RealInternalStore.java]: Agree, will fix that as well!

**Comment by pavlospt** [comment]
@digitalbuddha @brianPlummer @alexio @cybo42 Finished the PR review changes. Let me know what you think!

**Review by alexio — APPROVED** [review]

**Review by brianPlummer — APPROVED** [review]
